#Rename this file docker-compose.yml before use
#Tested with Rasperry Pi 4B 8GB running Ubuntu Server 20.10
 
version: '3.7'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./files:/input:ro
      - ./output_files:/output
    command: parsedmarc -c /parsedmarc.ini /input/*
    depends_on:
      elasticsearch:
         condition: service_healthy
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1-arm64
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false # required to prevent warnings in kibana dashboard. Security is not required as we're only operating docker-internally
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    healthcheck:
      test: [ "CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
# Set this to true to not require login
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
      GF_AUTH_ANONYMOUS_HIDE_VERSION: 'false'
      GF_AUTH_ANONYMOUS_ORG_NAME: DMARC-Reports
# Change Password to your taste. But CHANGE IT. Delete line for standard login credentials
      GF_SECURITY_ADMIN_PASSWORD: PASSWORD
# Opens Dashboard on login instead of manually selecting it
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/Grafana-DMARC_Reports.json
      
